# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kasir.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 81, 16))
        self.label.setObjectName("label")
        self.lineEditNamaBarang = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNamaBarang.setGeometry(QtCore.QRect(170, 60, 231, 22))
        self.lineEditNamaBarang.setObjectName("lineEditNamaBarang")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 90, 71, 16))
        self.label_2.setObjectName("label_2")
        self.lineEditHargaBarang = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditHargaBarang.setGeometry(QtCore.QRect(170, 90, 231, 22))
        self.lineEditHargaBarang.setObjectName("lineEditHargaBarang")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 120, 71, 16))
        self.label_3.setObjectName("label_3")
        self.lineEditJumlahBarang = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditJumlahBarang.setGeometry(QtCore.QRect(170, 120, 231, 22))
        self.lineEditJumlahBarang.setObjectName("lineEditJumlahBarang")
        self.pushButtonTambahBarang = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTambahBarang.setGeometry(QtCore.QRect(50, 150, 381, 28))
        self.pushButtonTambahBarang.setObjectName("pushButtonTambahBarang")
        self.tableWidgetBarang = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetBarang.setGeometry(QtCore.QRect(50, 180, 381, 192))
        self.tableWidgetBarang.setObjectName("tableWidgetBarang")
        self.tableWidgetBarang.setColumnCount(3)
        self.tableWidgetBarang.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBarang.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBarang.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBarang.setHorizontalHeaderItem(2, item)
        self.labelTotalHarga = QtWidgets.QLabel(self.centralwidget)
        self.labelTotalHarga.setGeometry(QtCore.QRect(50, 380, 381, 16))
        self.labelTotalHarga.setObjectName("labelTotalHarga")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 50, 421, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuAplikasi_Kasir_Sederhana = QtWidgets.QMenu(self.menubar)
        self.menuAplikasi_Kasir_Sederhana.setObjectName("menuAplikasi_Kasir_Sederhana")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAplikasi_Kasir_Sederhana.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Nama Barang"))
        self.label_2.setText(_translate("MainWindow", "Harga Barang"))
        self.label_3.setText(_translate("MainWindow", "Jumlah Barang"))
        self.pushButtonTambahBarang.setText(_translate("MainWindow", "Tambahkan Barang"))
        item = self.tableWidgetBarang.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nama Barang"))
        item = self.tableWidgetBarang.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Harga Barang"))
        item = self.tableWidgetBarang.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Jumlah Barang"))
        self.labelTotalHarga.setText(_translate("MainWindow", "Total Harga: 0.00"))
        self.menuAplikasi_Kasir_Sederhana.setTitle(_translate("MainWindow", "Aplikasi Kasir Sederhana"))
